name : Test datasets

on: 
  pull_request:
    branches:
      - main
    paths:
      - 's3_datasets.json'
jobs:
  test: # job name
    name: Run pytest
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      DOWNLOAD_PATH: ${{ secrets.DOWNLOAD_PATH }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    strategy:
      matrix:
         python-version: ["3.11.8"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version}}
    
    # - name: Install dependencies
    #   run : |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: Test preprocessing

      run: |
        python --version
      # pytest tests/preprocess.txt
    
    - name: Evaluate model on new dataset
      run: |
        python --version
      # python evaluate_model_on_new_dataset.py => compare to threshold fixed by team
      # if score < threshold wanted ==> 
      continue-on-error: true

    - name: Train model on new dataset
      if: ${{ failure() }} # Conditions to check if the previous step fails 
      run: |
        python --version
      # python train_model_new_dataset.py => if bleu score of trained model > existing ==> push to prod 

    - name: Upload pytest test result
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: test-results-${{ matrix.python-version }}.xml
      if: ${{ always() }}