name : Test model

on: 
  pull_request:
    branches:
      - main

jobs:
  test: # job name
    name: Run pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: ["3.11.8"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version}}
    
    # - name: Install dependencies
    #   run : |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: Run pytest
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: |
        python --version
        echo "$TEST_SECRET"
    - name: Upload pytest test result
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
      if: ${{ always() }}