name: Build model

on:  
  pull_request:
    branches:
      - model

jobs:
  # test:
  #   uses: markov-ngz/DEVIA_BLOC_2/.github/workflows/test_model.yml@main
  #   secrets: inherit
    
          
  evaluate: # for debugging purpose tests and evluate are divided into 2 jobs in order to run the second one without running the first
    needs: test
    uses: markov-ngz/DEVIA_BLOC_2/.github/workflows/evaluate_model.yml@main
    secrets: inherit
