name : Test model

on: 
  pull_request:
    branches:
      - main
    paths:
      - 's3_datasets.json'
      - '*.py'
jobs:
  test: # job name
    name: Run pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: ["3.11.8"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version}}
    
    # - name: Install dependencies
    #   run : |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: Run pytest
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        DOWNLOAD_PATH: ${{ secrets.DOWNLOAD_PATH }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      run: |
        python --version
    - name: Upload pytest test result
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: test-results-${{ matrix.python-version }}.xml
      if: ${{ always() }}