name: Validate model 

on:
  push:
    branches: [ "main" ]
    
jobs:
  setup_infra: 
    uses: markov-ngz/private-auto-github-runner/.github/workflows/register.yml@main
    with:
      repository: ${{ github.repository }}
    
  evaluate_model:
    needs: setup_infra
    runs-on: self-hosted
    steps:
      - name: Get public ip of the runner 
        run: curl -s ifconfig.me
        
  destroy_infra:
    needs: evaluate_model
    if:   needs.evaluate_model.result == 'success' || needs.evaluate_model.result == 'failure'
    uses: markov-ngz/private-auto-github-runner/.github/workflows/destroy.yml@main
