name: Package the model 

on: 
  pull_request:
    branches:
      - main 
jobs:

  package: 
    name: Package to docker
    if: ${{ github.head_ref == 'model' }}
    runs-on: ubuntu-latest
    env:
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      DOWNLOAD_PATH: ${{ secrets.DOWNLOAD_PATH }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version}}
      
      - name: Install dependencies
        run : |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download model and tokenizer
        run : | 
          python3 load_resources.py
          pwd
          ls -a
          ls model/
          ls tokenizer/

      - name: Login to Docker Hub
        uses: docker/login-action@v3  
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APPNAME }}:resources .
  
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APPNAME }}:resources
