name : Train model

on:
  workflow_dispatch: # input epoch number
    inputs:
      epochs:
        description: 'number of epochs to train the model on'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      DOWNLOAD_PATH: ${{ secrets.DOWNLOAD_PATH }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    strategy:
      matrix:
         python-version: ["3.11.8"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install dependencies
      run : |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Download model and tokenizer
      run: |
        python load_resources.py

    - name: Train model 
      run: |
        python main.py --epochs=$EPOCHS
      env: 
        EPOCHS: ${{inputs.epochs}}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3  
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APPNAME }}:ai_resource .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APPNAME }}:ai_resource
